=== MelihKotman/DBMS-Dersi/XML/katalog.dtd
<!-- Katalog DTD'si -->
<!-- | işareti birbirini takip eden öğelerden herhangi birinin var olabileceğini belirtir -->
<!-- * işareti sıfır veya daha fazla kez tekrar edebileceğini belirtir -->
<!ELEMENT katalog (kitaplar | plaklar)*> 
<!ELEMENT kitaplar (kitap)*>
<!ELEMENT plaklar (plak)*>

<!-- ? işareti öğenin isteğe bağlı olduğunu belirtir -->
<!ELEMENT kitap (yazar, baslik, tur?, fiyat)>

<!-- ATTLIST öğesi, bir öğenin sahip olabileceği nitelikleri tanımlar -->
<!ATTLIST kitap
    id CDATA #REQUIRED 
    baski CDATA #IMPLIED> 
<!-- id niteliği zorunludur -->
<!-- baski niteliği isteğe bağlıdır -->

<!-- #PCDATA, öğenin metin içerebileceğini belirtir -->
<!ELEMENT yazar (#PCDATA)>
<!ELEMENT baslik (#PCDATA)>
<!ELEMENT tur (#PCDATA)>
<!ELEMENT fiyat (#PCDATA)>

<!-- + işareti, öğenin bir veya daha fazla kez tekrar edebileceğini belirtir -->
<!ELEMENT plak (album, sarkici+, yili)>

<!ELEMENT album (#PCDATA)>
<!ELEMENT sarkici (#PCDATA)>
<!ELEMENT yili (#PCDATA)>

=== MelihKotman/DBMS-Dersi/XML/katalog.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE katalog SYSTEM "katalog.dtd"> 
<!-- Burada alınacak kurallar dizisi katalog.dtd dosyasından alınır -->
<katalog>
  <kitaplar>
    <!-- id niteliği zorunludur, baski niteliği isteğe bağlıdır -->
    <kitap id="bk1"> 
      <yazar>J. K. Rowling</yazar>
      <baslik>Harry Potter</baslik>
      <tur>Fantastik</tur>
      <fiyat>40</fiyat>
    </kitap>
    <!-- hem id hem de baski niteliği var -->
    <kitap id="bk2" baski="3. baski">
      <yazar>Miguel de Cervantes</yazar>
      <baslik>Don Kişot</baslik>
      <fiyat>50</fiyat>
    </kitap>
  </kitaplar>

  <plaklar>
    <!-- Birden fazla şarkıcıya sahip olabilir -->
    <plak>
      <album>Love for Sale</album>
      <sarkici>Tony Bennett</sarkici>
      <sarkici>Lady Gaga</sarkici>
      <yili>2021</yili>
    </plak>
    <plak>
      <album>Back in Black</album>
      <sarkici>AC/DC</sarkici>
      <yili>1980</yili>
    </plak>
  </plaklar>
</katalog>
